/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kalkulatorsederhana;

import com.sun.java.swing.plaf.windows.WindowsLookAndFeel;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.script.ScriptEngine;
import javax.script.ScriptEngineManager;
import javax.script.ScriptException;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import org.jsoup.Jsoup;

/**
 *
 * @author Win_8.1
 */
public class KalkulatorSederhana extends javax.swing.JFrame {

    /**
     * Creates new form KalkulatorDasarForm
     */
    
    StringBuilder sb = new StringBuilder(64);
    public boolean stSymbol, stResult = false;
    public String calcValue = "";
    
    public KalkulatorSederhana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        clearAll = new javax.swing.JButton();
        empat = new javax.swing.JButton();
        satu = new javax.swing.JButton();
        persen = new javax.swing.JButton();
        tujuh = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        delapan = new javax.swing.JButton();
        lima = new javax.swing.JButton();
        dua = new javax.swing.JButton();
        nol = new javax.swing.JButton();
        sembilan = new javax.swing.JButton();
        bagi = new javax.swing.JButton();
        enam = new javax.swing.JButton();
        tiga = new javax.swing.JButton();
        koma = new javax.swing.JButton();
        kali = new javax.swing.JButton();
        hasil = new javax.swing.JButton();
        kurang = new javax.swing.JButton();
        tambah = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        output = new javax.swing.JLabel();

        jLabel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(280, 455));
        setResizable(false);
        setSize(new java.awt.Dimension(280, 425));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Kalkulator Sederhana");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        clearAll.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        clearAll.setText(" C ");
        clearAll.setFocusable(false);
        clearAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearAllActionPerformed(evt);
            }
        });
        getContentPane().add(clearAll, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, 42));

        empat.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        empat.setText("4");
        empat.setFocusable(false);
        empat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empatActionPerformed(evt);
            }
        });
        getContentPane().add(empat, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 55, 42));

        satu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        satu.setText("1");
        satu.setFocusable(false);
        satu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                satuActionPerformed(evt);
            }
        });
        getContentPane().add(satu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 55, 42));

        persen.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        persen.setText("%");
        persen.setFocusable(false);
        persen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                persenActionPerformed(evt);
            }
        });
        getContentPane().add(persen, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 55, 42));

        tujuh.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tujuh.setText("7");
        tujuh.setFocusable(false);
        tujuh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tujuhActionPerformed(evt);
            }
        });
        getContentPane().add(tujuh, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 55, 42));

        clear.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        clear.setText("<");
        clear.setFocusable(false);
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        getContentPane().add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 55, 42));

        delapan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        delapan.setText("8");
        delapan.setFocusable(false);
        delapan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delapanActionPerformed(evt);
            }
        });
        getContentPane().add(delapan, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 55, 42));

        lima.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lima.setText("5");
        lima.setFocusable(false);
        lima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limaActionPerformed(evt);
            }
        });
        getContentPane().add(lima, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 55, 42));

        dua.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        dua.setText("2");
        dua.setFocusable(false);
        dua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                duaActionPerformed(evt);
            }
        });
        getContentPane().add(dua, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, 55, 42));

        nol.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nol.setText("0");
        nol.setFocusable(false);
        nol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nolActionPerformed(evt);
            }
        });
        getContentPane().add(nol, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, 55, 42));

        sembilan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sembilan.setText("9");
        sembilan.setFocusable(false);
        sembilan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sembilanActionPerformed(evt);
            }
        });
        getContentPane().add(sembilan, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 55, 42));

        bagi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bagi.setText("/");
        bagi.setFocusable(false);
        bagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bagiActionPerformed(evt);
            }
        });
        getContentPane().add(bagi, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 55, 42));

        enam.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        enam.setText("6");
        enam.setFocusable(false);
        enam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enamActionPerformed(evt);
            }
        });
        getContentPane().add(enam, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 55, 42));

        tiga.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tiga.setText("3");
        tiga.setFocusable(false);
        tiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tigaActionPerformed(evt);
            }
        });
        getContentPane().add(tiga, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, 55, 42));

        koma.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        koma.setText(".");
        koma.setFocusable(false);
        koma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                komaActionPerformed(evt);
            }
        });
        getContentPane().add(koma, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, 55, 42));

        kali.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        kali.setText("X");
        kali.setFocusable(false);
        kali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kaliActionPerformed(evt);
            }
        });
        getContentPane().add(kali, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 55, 42));

        hasil.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        hasil.setText("=");
        hasil.setFocusable(false);
        hasil.setMaximumSize(new java.awt.Dimension(45, 38));
        hasil.setMinimumSize(new java.awt.Dimension(45, 38));
        hasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hasilActionPerformed(evt);
            }
        });
        getContentPane().add(hasil, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, 55, 92));

        kurang.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        kurang.setText("-");
        kurang.setFocusable(false);
        kurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kurangActionPerformed(evt);
            }
        });
        getContentPane().add(kurang, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 55, 42));

        tambah.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tambah.setText("+");
        tambah.setFocusable(false);
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });
        getContentPane().add(tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 55, 42));

        output.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        output.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        output.setText("0");
        output.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        output.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 15));
        jScrollPane1.setViewportView(output);
        output.getAccessibleContext().setAccessibleName("");

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 280, 120));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clearAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearAllActionPerformed
        // TODO add your handling code here:
        stSymbol = false;
        stResult = false;
        calcValue = "0";
        output.setText("0");
    }//GEN-LAST:event_clearAllActionPerformed

    private void empatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empatActionPerformed
        // TODO add your handling code here:
        showNumber("4");
    }//GEN-LAST:event_empatActionPerformed

    private void satuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_satuActionPerformed
        // TODO add your handling code here:
        showNumber("1");
    }//GEN-LAST:event_satuActionPerformed

    private void persenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_persenActionPerformed
        // TODO add your handling code here:
        showSymbol("/ 100 *", "%");
    }//GEN-LAST:event_persenActionPerformed

    private void tujuhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tujuhActionPerformed
        // TODO add your handling code here:
        showNumber("7");
    }//GEN-LAST:event_tujuhActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        String outValue = output.getText();
        outValue = outValue.substring(0, outValue.length()-2);
        
        if(stSymbol == true){
            stSymbol = false;
        } else{
            stSymbol = true;
        }
        
        calcValue = calcValue.substring(0, calcValue.length()-2);
        output.setText(outValue);
    }//GEN-LAST:event_clearActionPerformed

    private void delapanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delapanActionPerformed
        // TODO add your handling code here:
        showNumber("8");
    }//GEN-LAST:event_delapanActionPerformed

    private void limaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limaActionPerformed
        // TODO add your handling code here:
        showNumber("5");
    }//GEN-LAST:event_limaActionPerformed

    private void duaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_duaActionPerformed
        // TODO add your handling code here:
        showNumber("2");
    }//GEN-LAST:event_duaActionPerformed

    private void nolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nolActionPerformed
        // TODO add your handling code here:
        showNumber("0");
    }//GEN-LAST:event_nolActionPerformed

    private void hasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hasilActionPerformed
        // TODO add your handling code here:
        String outValue = output.getText();
        
        ScriptEngineManager mgr = new ScriptEngineManager();
        ScriptEngine engine = mgr.getEngineByName("JavaScript");
        String allOut = Jsoup.parse(calcValue).text();
        Number finalResult = 0;
        try {
            finalResult = (Number) engine.eval(allOut);
            stResult = true;
        } catch (ScriptException ex) {
            Logger.getLogger(KalkulatorSederhana.class.getName()).log(Level.SEVERE, null, ex);
        }
        output.setText("<html>" + outValue + "<br/>= " + finalResult + "</html>");
    }//GEN-LAST:event_hasilActionPerformed

    private void tigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tigaActionPerformed
        // TODO add your handling code here:
        showNumber("3");
    }//GEN-LAST:event_tigaActionPerformed

    private void enamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enamActionPerformed
        // TODO add your handling code here:
        showNumber("6");
    }//GEN-LAST:event_enamActionPerformed

    private void sembilanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sembilanActionPerformed
        // TODO add your handling code here:
        showNumber("9");
    }//GEN-LAST:event_sembilanActionPerformed

    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
        // TODO add your handling code here:
        showSymbol("+", "+");
    }//GEN-LAST:event_tambahActionPerformed

    private void kurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kurangActionPerformed
        // TODO add your handling code here:
        showSymbol("-", "-");
    }//GEN-LAST:event_kurangActionPerformed

    private void kaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kaliActionPerformed
        // TODO add your handling code here:
        showSymbol("*", "x");
    }//GEN-LAST:event_kaliActionPerformed

    private void bagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bagiActionPerformed
        // TODO add your handling code here:
        showSymbol("/", "/");
    }//GEN-LAST:event_bagiActionPerformed

    private void komaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_komaActionPerformed
        // TODO add your handling code here:
        String outValue = output.getText();
        if(outValue.equals("0") || stResult == true){
            calcValue = "0.";
            output.setText("0.");
        } else{
            if(stSymbol == true){
                calcValue = "0.";
                output.setText("0.");
            } else{
                calcValue = calcValue + ".";
                output.setText(outValue + ".");
            }
        }
        stSymbol = false;
        
        kali.setEnabled(false);
        clear.setEnabled(false);
        bagi.setEnabled(false);
        tambah.setEnabled(false);
        kurang.setEnabled(false);
        persen.setEnabled(false);
        hasil.setEnabled(false);
    }//GEN-LAST:event_komaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(new WindowsLookAndFeel());
        } catch (UnsupportedLookAndFeelException ex) {
            JOptionPane.showMessageDialog(null, "Sistem Operasi Anda Tidak Mendukung Tampilan Aplikasi ini, Tampilan Akan Berubah Menjadi Default..", "Perhatian", JOptionPane.ERROR_MESSAGE);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KalkulatorSederhana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bagi;
    private javax.swing.JButton clear;
    private javax.swing.JButton clearAll;
    private javax.swing.JButton delapan;
    private javax.swing.JButton dua;
    private javax.swing.JButton empat;
    private javax.swing.JButton enam;
    private javax.swing.JButton hasil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton kali;
    private javax.swing.JButton koma;
    private javax.swing.JButton kurang;
    private javax.swing.JButton lima;
    private javax.swing.JButton nol;
    private javax.swing.JLabel output;
    private javax.swing.JButton persen;
    private javax.swing.JButton satu;
    private javax.swing.JButton sembilan;
    private javax.swing.JButton tambah;
    private javax.swing.JButton tiga;
    private javax.swing.JButton tujuh;
    // End of variables declaration//GEN-END:variables
    
    private String showNumber(String number){
        String result = "";
        
        String outValue = output.getText();
        if(outValue.equals("0") || stResult == true){
            output.setText(number);
            calcValue = number;
            stResult = false;
        } else{
            if(stSymbol == false){
                output.setText(outValue + number);
                calcValue = calcValue + number;
            } else{
                output.setText(outValue + " " + number);
                calcValue = calcValue + " " + number;
            }
        }
        stSymbol = false;
        
        if(!hasil.isEnabled()){
            kali.setEnabled(true);
            clear.setEnabled(true);
            bagi.setEnabled(true);
            tambah.setEnabled(true);
            kurang.setEnabled(true);
            persen.setEnabled(true);
            hasil.setEnabled(true);
        }
        
        return result;
    }
    
    private String showSymbol(String symbol, String alias){
        String result = "";
        
        String outValue = output.getText();
        if(!outValue.equals("0") || stResult == true){
            if(stSymbol == true){
                outValue = outValue.substring(0, outValue.length()-2);
            }
            calcValue = calcValue + " " + symbol;
            output.setText(outValue + " " + alias);
            stSymbol = true;
        }
        
        return result;
    }

}
